<?php
	DEFINE('PAGE_HOOK_EVARISK_ACCEUIL', 'evarisk-acceuil');
	DEFINE('PAGE_HOOK_EVARISK_OPTIONS_GENERALES', 'evarisk-options-generales');
	DEFINE('PAGE_HOOK_EVARISK_PAGE_DANGER', 'evarisk-page-dangers');
	DEFINE('PAGE_HOOK_EVARISK_CATEGORIES_DANGERS', 'evarisk-categorie-dangers');
	DEFINE('PAGE_HOOK_EVARISK_DANGERS', 'evarisk-dangers');
	DEFINE('PAGE_HOOK_EVARISK_EVALUATION_DES_RISQUES', 'evarisk-evaluation-des-risques');
	DEFINE('PAGE_HOOK_EVARISK_UNITES_DE_TRAVAIL', 'evarisk-unites-de-travail');
	DEFINE('PAGE_HOOK_EVARISK_UNITES_DE_TRAVAIL_GESTION', 'evarisk-unites-de-travail-gestion');
	DEFINE('PAGE_HOOK_EVARISK_GROUPEMENTS', 'evarisk-groupements');
	DEFINE('PAGE_HOOK_EVARISK_GROUPEMENTS_GESTION', 'evarisk-groupements-gestion');
	DEFINE('PAGE_HOOK_EVARISK_VEILLE_CREATION', 'evarisk-veille-creation');
	DEFINE('PAGE_HOOK_EVARISK_ATTRIBUTS_UTILISATEURS', 'evarisk-attributs-utilisateurs');
	DEFINE('PAGE_HOOK_EVARISK_TACHE', 'evarisk-taches');
	DEFINE('PAGE_HOOK_EVARISK_ACTIVITE', 'evarisk-activite');
	DEFINE('PAGE_HOOK_EVARISK_PRECONISATION', 'evarisk-recommandation');
	DEFINE('PAGE_HOOK_EVARISK_EVALUATION_METHODE', 'evarisk-evaluation_method');
	DEFINE('PAGE_HOOK_EVARISK_MENU', 'evarisk-menus');
	DEFINE('PAGE_HOOK_EVARISK_CATEGORIE_PRECONISATION', 'evarisk-categories_recommandation');